### ISSUE TITLE
Maquetación Inicial

### ISSUE THREAD

**Issue by RobertoMoriyon** [RobertoMoriyon/Olloniego#3]
Crear una maquetación inicial funcional, que incluya:
- [ ] Index
- [ ] Página de la plantilla del equipo
- [ ] Página de Calendario
- [ ] Página de Resultados
- [ ] Página de Clasificación
- [ ] Página de Convocatoria
- [ ] Página del Club
- [ ] Página de Estadisticas
- [ ] Log In
